version = 1

test_patterns = [
    "*_test.go",
    "**/*_test.go",
    "**/**/*_test.go",
    "**/**/**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true 

  [analyzers.meta]
  import_path = "github.com/bench-routes/bench-routes"
