password: your password
utils:
  monitor-length:
    mode: 0
    mean: 0
  services-state:
    ping: passive
    flood-ping: passive
    jitter: passive
    req-res-delay-or-monitoring: passive
test_interval:
- test: ping
  type: sec
  duration: 20
- test: jitter
  type: sec
  duration: 15
- test: monitoring
  type: sec
  duration: 3
routes:
- method: GET
  url: https://www.facebook.com/search
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
  body: []
- method: GET
  url: https://in.search.yahoo.com/search
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: p
    value: bench-routes
  - name: fp
    value: "1"
  - name: toggle
    value: "1"
  - name: cop
    value: mss
  - name: ei
    value: UTF-8
  body: []
- method: GET
  url: https://reqres.in/api/unknown
  headers: []
  params: []
  body: []
- method: GET
  url: http://dummy.restapiexample.com/api/v1/employees
  headers: []
  params: []
  body: []
- method: GET
  url: https://www.bing.com/search?q=bench-routes&qs=n&form=QBRE&sp=-1&pq=bench-rotes&sc=8-11&sk=&cvid=63660D91E0DD40329FC8123C78DBACE2
  headers: []
  params: []
  body: []
- method: GET
  url: https://material-ui.com/components/popover/
  headers: []
  params: []
  body: []
- method: GET
  url: https://hangouts.google.com/
  headers: []
  params: []
  body: []
- method: POST
  url: https://reqres.in/api/register
  headers: []
  params: []
  body:
  - name: ""
    value: ""
  - name: email
    value: eve.holt@reqres.in
  - name: password
    value: pistol
- method: GET
  url: https://google.com
  headers: []
  params: []
  body: []
- method: POST
  url: https://www.google.co.in/search
  headers: []
  params: []
  body: []
- method: GET
  url: https://www.google.co.in/search
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
  body: []
- method: GET
  url: https://www.google.co.in/about
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
  body: []
- method: GET
  url: https://reqres.in/api/user
  headers: []
  params:
  - name: page
    value: "2"
  - name: undefined
    value: ""
  body: []
- method: GET
  url: https://reqres.in/api/users/3
  headers: []
  params: []
  body: []
- method: GET
  url: https://www.youtube.com/
  headers: []
  params: []
  body: []
- method: GET
  url: https://www.youtube.com/watch?v=ga1ccmEJuSM
  headers: []
  params: []
  body: []
- method: GET
  url: https://msn.com
  headers: []
  params: []
  body: []
- method: GET
  url: https://postman-echo.com/
  headers: []
  params: []
  body: []
- method: GET
  url: https://reqbin.com/req/nfilsyk5/get-request-example
  headers: []
  params: []
  body: []
- method: GET
  url: https://muskankhedi.github.io/
  headers: []
  params: []
  body: []
